language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: kTN4E9/AWZv5Zx97MZWOoPjpuB4GK3fshf9OjcjwVg8FrP2eVm/a68zq7DjMBcDwsHaV+cX7LVcHadtYGXCgoLP36j9r2lmKgLjcCWF1I7D89TeGRVoBfGxMfOSizbaoTgMeMfTIdpPoI1UgVxdzixOYJwwJ/bUDMs3wq/u2cxlAa+BullhyWpo7yTh4xjH8wXmGb44VvtOgfgjizSgo5rBeiFgf9LQZqihm74N1gkYP3dnWqFQR8UibrIOMno4ESGifuTTbWkP5DkTLiin8TEOMFwPxeLoYUQUtojdBRayjQxkF1JQv9XsQnGm54ZuJ3H17rRLsw0wcqGlEqfoybU1OKyIPRKE+YWDS4ajtiGfqOAl8bWAHdCQU3QK4mSQ/lImctwyDDfPtPcjJn8t4XkSdQIxnV5btq0784KgLsqzapBVuzzASTcMyCmNAwoG7DLGN6QhsKWfOyoUWKWJ/yA9s+iNmXQcBRYyXksO7Xldrh/max7PR2scfaJJdpR0+8N3Gta0vAkNKRckVkdw7oXooal0VLRS77xUQiJaygxG56ErX8Meb3SrwMs89EkFBMAHyFX+EXeEBvQ6vAXYBX1a7fEnK+M8gH8EvGPhqY4vBYtPrO+Kn6QSlN4xxQMQ4PPsNCcIECUeF7Gkm9bTMTvFKSP6ztmVTTBX5zQHm7p4=
  app: tron-09-2016
  on:
    repo: BOG8/tron-09-2016
